"""changed excuses

Revision ID: 2d8314226fa4
Revises: 79dd93cc67bc
Create Date: 2018-03-13 11:55:51.968697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d8314226fa4'
down_revision = '79dd93cc67bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_believable', sa.Text(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Excuses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Excuses',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Excuses_id_seq"\'::regclass)'), nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_believable', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='Excuses_student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Excuses_pkey')
    )
    op.drop_table('excuses')
    # ### end Alembic commands ###
